# Generated by Django 5.2.14 on 2026-05-24 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('lesson_number', models.IntegerField(verbose_name='Номер урока')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='Кабинет')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classgroup', verbose_name='Класс')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day_of_week', 'lesson_number'],
                'unique_together': {('day_of_week', 'lesson_number', 'class_group')},
            },
        ),
    ]
