# Generated by Django 5.2.14 on 2026-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('Уроки', 'Уроки'), ('Мероприятия', 'Мероприятия'), ('Олимпиады', 'Олимпиады'), ('Проекты', 'Проекты'), ('Другое', 'Другое')], default='Другое', max_length=50),
        ),
    ]
