# Generated by Django 5.2.14 on 2026-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Ученик')], default='student', max_length=10),
        ),
    ]
